hooks:
  release:
    pre:
      - gulp coffee
  gh_pages:
    pre:
      - gulp yuidoc
config:
  git-user-name: CircleCI
  git-user-email: circleci@cureapp.jp
  version-prefix: v
  create-branch: false
  create-gh-pages: true
  gh-pages-dir: doc
  npm_update_depth: 3
  npm_shrinkwrap: true
circle:
  machine:
    timezone: Asia/Tokyo
    node:
      version: 4.2.1
  notify:
    webhooks:
      - url: 'https://script.google.com/macros/s/AKfycbwJJOSKRGQYeyWDqiOCrmUOoBZ2xHsXFWFGZXLyhKcKEFPcWg8M/exec'
