hooks:
  release:
    pre:
      - gulp coffee
  gh_pages:
    pre:
      - gulp yuidoc
config:
  git_user_name: CircleCI
  git_user_email: circleci@cureapp.jp
  version_prefix: v
  create_branch: false
  create_gh_pages: true
  gh_pages_dir: doc
  npm_update_depth: 3
  npm_shrinkwrap: false
circle:
  machine:
    environment:
      NODE_ENV:
    timezone: Asia/Tokyo
    node:
      version: 4.2.1
  notify:
    webhooks:
      - url: "https://script.google.com/macros/s/AKfycbwJJOSKRGQYeyWDqiOCrmUOoBZ2xHsXFWFGZXLyhKcKEFPcWg8M/exec"
