###
generated by base-domain generator
###

BaseModel = require('base-domain').BaseModel

###*
entity class of non-entity

@class NonEntity
@extends BaseModel
###
class NonEntity extends BaseModel

    @properties:
        name      : @TYPES.STRING

module.exports = NonEntity
