###
generated by base-domain generator
###


BaseRepository = require('base-domain').BaseRepository

###*
repository of instrument

@class InstrumentRepository
@extends BaseRepository
###
class InstrumentRepository extends BaseRepository

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: 'instrument'

module.exports = InstrumentRepository
