###
generated by base-domain generator
###


BaseFactory = require('base-domain').BaseFactory


###*
factory of live-info

@class LiveInfoFactory
@extends BaseFactory
###
class LiveInfoFactory extends BaseFactory

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: 'live-info'

module.exports = LiveInfoFactory
