###
generated by base-domain generator
###


BaseFactory = require('base-domain').BaseFactory


###*
factory of player

@class PlayerFactory
@extends BaseFactory
###
class PlayerFactory extends BaseFactory

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: 'player'

module.exports = PlayerFactory
