###
generated by base-domain generator
###


BaseRepository = require('base-domain').BaseRepository

###*
repository of song

@class SongRepository
@extends BaseRepository
###
class SongRepository extends BaseRepository

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: 'song'

module.exports = SongRepository
