###
generated by base-domain generator
###


BaseFactory = require('base-domain').BaseFactory


###*
factory of non-entity

@class NonEntityFactory
@extends BaseFactory
###
class NonEntityFactory extends BaseFactory

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: 'non-entity'

module.exports = NonEntityFactory
