###
generated by base-domain generator
###

BaseList = require('base-domain').BaseList

###*
entity class of set-list

@class SetList
@extends Entity
###
class SetList extends BaseList

    @itemModelName: 'song'

module.exports = SetList
